io:
  augmentation_level: 2
  datadir: data/Recurvps
  dataset: RP 
  focal_length: 2.408333333333333
  logdir: logs/
  num_vpts: 1
  num_workers: 6
  resume_from: logs/190522-040435-de95f53-scannet-conic6
  tensorboard_port: 0
  validation_debug: 240
  validation_interval: 24000
model:
  backbone: stacked_hourglass
  batch_size: 6
  conic_6x: true
  depth: 4
  fc_channel: 1024
  im2col_step: 21
  multires:
  - 0.02004838034795
  - 0.0774278195486317
  - 0.299564810864565
  num_blocks: 1
  num_stacks: 1
  num_steps: 4
  output_stride: 4
  smp_multiplier: 2
  smp_neg: 1
  smp_pos: 1
  smp_rnd: 3
  upsample_scale: 1
optim:
  amsgrad: true
  lr: 0.0001
  lr_decay_epoch: 3
  max_epoch: 36
  name: Adam
  weight_decay: 1.0e-05
