io:
  augmentation_level: 2
  datadir: data/tmm17/
  dataset: TMM17
  focal_length: 1.0
  logdir: logs/
  num_vpts: 1
  num_workers: 4
  resume_from: logs/200107-013044-14545f5-tmm17-bugfix-lr1e-4-long
  tensorboard_port: 0
  validation_debug: 0
  validation_interval: 8000
model:
  backbone: stacked_hourglass
  batch_size: 8
  conic_6x: false
  depth: 4
  fc_channel: 1024
  im2col_step: 11
  multires:
  - 0.0051941870036646
  - 0.02004838034795
  - 0.0774278195486317
  - 0.299564810864565
  num_blocks: 1
  num_stacks: 1
  output_stride: 4
  smp_multiplier: 2
  smp_neg: 1
  smp_pos: 1
  smp_rnd: 3
  upsample_scale: 1
optim:
  amsgrad: true
  lr: 0.0001
  lr_decay_epoch: 60
  max_epoch: 100
  name: Adam
  weight_decay: 0.0006
